name: Rebuild GitHub Pages

on:
  workflow_run:
    workflows: ["Update Weather Data"]
    types:
      - completed

jobs:
  rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create empty commit to trigger rebuild
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit --allow-empty -m "Trigger GitHub Pages rebuild"
          git push