name: Update Weather Data

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  # Also allow manual triggers
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install node-fetch@2
      
      - name: Fetch weather data
        run: node .github/scripts/fetch-weather.js
        
      - name: Commit and push if data changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/weather.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update weather data"
          git push